version: "3.9"

services:
    db:
        network_mode: host
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: samplesecretpassword
    redis:
        network_mode: host
        image: "redis:alpine"
        ports:
            - "6379:6379"
        restart: always

    auth_service:
        container_name: "microservice_project_demo_auth_service"
        restart: always
        network_mode: host
        build:
            context: .
            dockerfile: ./auth_service.Dockerfile
        ports:
            - "8000:8000"

    blog_service:
        container_name: "microservice_project_demo_blog_service"
        restart: always
        network_mode: host
        build:
            context: .
            dockerfile: ./blog_service.Dockerfile
        ports:
            - "8001:8001"
