version: "3.9"

services:
    db:
        network_mode: host
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: samplesecretpassword
    redis:
        network_mode: host
        image: "redis:alpine"
        ports:
            - "6379:6379"
        restart: always
